Free rtos queues
ETCLabs/EtcPal pull request #37
Opened 2020-08-11 21:15 UTC by BarrettLowe

This allows freertos queues to be used via EtcPal

2020-08-11 22:04 UTC, samkearney requested changes
Thanks for the work! These are almost all style and organization nitpicks.

2020-08-11 22:04 UTC, samkearney commented on include/etcpal/cpp/rtos/pal_queue.h
> +/// \file etcpal/cpp/rtos/pal_queue.h
This file should be `etcpal/cpp/queue.h`

2020-08-11 22:04 UTC, samkearney commented on include/etcpal/cpp/rtos/pal_queue.h
> +#ifndef ETCPAL_CPP_RTOS_ERROR_H
`ETCPAL_CPP_QUEUE_H_`

2020-08-11 22:04 UTC, samkearney commented on include/etcpal/cpp/rtos/pal_queue.h
> +  bool AddToQueue_from_isr(const T& data) { return etcpal_queue_add_from_isr(&m_queueHandle, &data); }
These functions should all be consistent CamelCase: `AddToQueueFromIsr()`

2020-08-11 22:04 UTC, samkearney commented on include/etcpal/cpp/rtos/pal_queue.h
> +  explicit Queue(unsigned size) { etcpal_queue_create(&m_queueHandle, size, sizeof(T)); }
To follow the style of the other C++ headers, we shouldn't have any function definitions inside the class definition. They should be defined inline below the class, with doc comments. Take a look at one of the other cpp headers for an example.

2020-08-11 22:04 UTC, samkearney commented on include/etcpal/rtos/pal_queue.h
> +/******************************************************************************
This file should be `etcpal/queue.h`

2020-08-11 22:04 UTC, samkearney commented on include/etcpal/rtos/pal_queue.h
> +#ifndef ETCPAL_RTOS_QUEUE_H_
`ETCPAL_QUEUE_H_`

2020-08-11 22:04 UTC, samkearney commented on include/os/freertos/etcpal/os_queue.h
> +#include "queue.h"
Is this the FreeRTOS queue header? If so, it should probably be in brackets <> to match FreeRTOS.h (or they should both be in quotes - just consistent either way).

2020-08-11 22:04 UTC, samkearney commented on include/os/freertos/etcpal/os_queue.h
> +bool etcpal_queue_add(etcpal_queue_t* id, const void* data, unsigned timeout_ms);
For consistency with our other similar OS abstraction functions, would you be willing to change this to:
```
bool etcpal_queue_add(etcpal_queue_t* id, const void* data); // Add, blocking forever
bool etcpal_queue_timed_add(etcpal_queue_t* id, const void* data, int timeout_ms); // Add with a timeout
```

2020-08-11 22:04 UTC, samkearney commented on include/os/freertos/etcpal/os_queue.h
> +bool etcpal_queue_get(etcpal_queue_t* id, void* data, unsigned timeout_ms);
Same comment as above for changing the names of the blocking/non-blocking functions.

Also, I'm a fan of "opposite" words for functions like these -- "add" and "get" are not strictly opposites, so it would be preferable for it to be something like "push/pop", "send/receive", "add/remove", "queue/dequeue", etc... whatever you think is best.

2020-08-11 22:04 UTC, samkearney commented on src/os/freertos/etcpal/os_queue.c
> +#include "projdefs.h"
What's "projdefs.h"? Is that a FreeRTOS header?

2020-08-11 22:04 UTC, samkearney commented on src/os/freertos/etcpal/os_queue.c
> +bool etcpal_queue_create(etcpal_queue_t* id, unsigned size, unsigned item_size)
For consistency with the rest of the library, I'm thinking size parameters should be `size_t`, and timeout parameters should be `int`

2020-08-12 15:03 UTC, BarrettLowe commented on src/os/freertos/etcpal/os_queue.c
> +bool etcpal_queue_create(etcpal_queue_t* id, unsigned size, unsigned item_size)
Sure. Timeout should be signed? I can change it

2020-08-12 15:08 UTC, samkearney commented on src/os/freertos/etcpal/os_queue.c
> +bool etcpal_queue_create(etcpal_queue_t* id, unsigned size, unsigned item_size)
Yes - for timeout parameters we allow the passage of a special constant ETCPAL_WAIT_FOREVER (defined to -1) which means block indefinitely.

2020-08-13 14:58 UTC, samkearney commented
/AzurePipelines build

2020-08-13 14:58 UTC, samkearney commented
/AzurePipelines run

2020-08-13 15:07 UTC, samkearney requested changes
Thanks, all the changes so far and the unit tests look great. Let's add some unit tests for the C++ version as well, just to make sure it's working. Check out tests/unit/cpp for some existing examples. Note you'll probably have to do the same thing with the CMake conditional inclusion as with the live unit tests to make sure the queue tests don't get built on platforms that they're not supported on.

2020-08-17 14:15 UTC, merged